package com.jbk.bean;
// Generated 17 Aug, 2020 9:18:42 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name = "employee", catalog = "springhibernate")
public class Employee implements java.io.Serializable {

	private Integer eid;
	private Country country;
	private String ename;
	private String status;
	private String department;
	private String phoneno;

	public Employee() {
	}

	public Employee(Country country, String ename, String status, String department, String phoneno) {
		this.country = country;
		this.ename = ename;
		this.status = status;
		this.department = department;
		this.phoneno = phoneno;
	}

	@GenericGenerator(name = "com.jbk.bean.EmployeeIdGenerator", strategy = "foreign", parameters = @Parameter(name = "property", value = "country"))
	@Id
	@GeneratedValue(generator = "com.jbk.bean.EmployeeIdGenerator")

	@Column(name = "eid", unique = true, nullable = false)
	public Integer getEid() {
		return this.eid;
	}

	public void setEid(Integer eid) {
		this.eid = eid;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Country getCountry() {
		return this.country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	@Column(name = "ename", nullable = false, length = 45)
	public String getEname() {
		return this.ename;
	}

	public void setEname(String ename) {
		this.ename = ename;
	}

	@Column(name = "status", nullable = false, length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "department", nullable = false, length = 45)
	public String getDepartment() {
		return this.department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	@Column(name = "phoneno", nullable = false, length = 45)
	public String getPhoneno() {
		return this.phoneno;
	}

	public void setPhoneno(String phoneno) {
		this.phoneno = phoneno;
	}

}
